---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      # 1 step. Logs into Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 2 step. Check out using the checkout
      - name: Checkout
        uses: actions/checkout@v2
      # 3 step. Run the test using Docker Compose
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      # 4 step. Run the linting using Docker compose as well
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"